package:
  name: q
  version: 3.6

build:
  number: auto
  string: {{ QBUILD }}
  script:
    - OSL=l #[linux]
    - OSL=m #[osx]
    - mkdir -p "${PREFIX}"/etc/conda/{de,}activate.d/
    - cp "${RECIPE_DIR}"/activate.sh "${PREFIX}"/etc/conda/activate.d/"${PKG_NAME}"_activate.sh
    - cp "${RECIPE_DIR}"/deactivate.sh "${PREFIX}"/etc/conda/deactivate.d/"${PKG_NAME}"_deactivate.sh
    - QHOME=$PREFIX/q
    - mkdir -p $QHOME/${OSL}64
    - cp $SRC_DIR/${OSL}64/q $QHOME/${OSL}64
    - cp $SRC_DIR/q.k $QHOME
    - cp $SRC_DIR/kc.lic $QHOME
    - echo -e '#!/bin/bash \n numactl --physcpubind=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 $QHOME/l64/q "$@"' > $PREFIX/bin/q16
    - chmod +x $PREFIX/bin/q16
    - ln $QHOME/${OSL}64/q $PREFIX/bin/q

source:
  - path: ./
  - url: file:///{{ QLICSRC }}/kc.lic
  - url: file:///{{ QZIP }}/l64.zip


test:
  commands:
    - test -f $QHOME/kc.lic
    - test -d $QHOME
    - test -f $QEXE
    - echo exit 0 | numactl --physcpubind=0 $QEXE -q # [linux64]
    - echo exit 0 | q16 -q # [linux64]

about:
  home: https://kx.com/
  license: Commercial
  summary: q/kdb+
