package:
  name: qml
  version: 0.7.3

source:
  - git_url: https://github.com/zholos/qml.git
    git_tag: v0.7.3
    git_depth: 1
  - path: ./

requirements:
  build:
    - q
    - qutil
  run:
    - q
    - qutil

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  script:
    - mkdir -p "${QPATH}"/"${PKG_NAME}"
    - echo ".utl.pkg\"qml.q\"" > init.q && cp init.q "${QPATH}"/"${PKG_NAME}"
    - cp "${SRC_DIR}"/src/qml.q "${QPATH}"/"${PKG_NAME}"
    - ./configure --build-blas
    - make
    - cp "${SRC_DIR}"/src/qml.so "${QHOME}"/l64 #[linux and x86_64]

test:
  requires:
    - q
    - qutil
  commands:
    - test -d "${QPATH}"/qml
    - echo ".utl.require\"qml\";.qml.nicdf .25" | q16 -q

about:
  home: http://althenia.net/qml
  license: BSD
  license_file: LICENSE.txt
  summary: math library for kdb+
